export type Category = "transfer" | "adrenaline" | "excursion" | "desert";

export interface Activity {
  id: string;
  category: Category;
  slug: string;
  nameKey: string;
  price: number;
  currency: string;
  durationFr: string;
  durationEn: string;
  durationAr: string;
  durationEs: string;
  descriptionFr: string;
  descriptionEn: string;
  descriptionAr: string;
  descriptionEs: string;
  includesFr: string[];
  includesEn: string[];
  includesAr: string[];
  includesEs: string[];
  gradient: string;
  accentColor: string;
  featured?: boolean;
}

export const activities: Activity[] = [
  // TRANSFER
  {
    id: "airport-transfer",
    category: "transfer",
    slug: "transfert-aeroport",
    nameKey: "Transfert Aéroport",
    price: 15,
    currency: "€",
    durationFr: "30 min",
    durationEn: "30 min",
    durationAr: "30 دقيقة",
    durationEs: "30 min",
    descriptionFr: "Transfert privé et confortable depuis/vers l'aéroport Marrakech-Menara. Chauffeur professionnel, ponctualité garantie.",
    descriptionEn: "Private and comfortable transfer to/from Marrakech-Menara Airport. Professional driver, punctuality guaranteed.",
    descriptionAr: "نقل خاص ومريح من/إلى مطار مراكش المنارة. سائق محترف، والالتزام بالمواعيد مضمون.",
    descriptionEs: "Traslado privado y cómodo desde/hacia el aeropuerto Marrakech-Menara. Conductor profesional, puntualidad garantizada.",
    includesFr: ["Chauffeur professionnel", "Véhicule climatisé", "Suivi de vol", "Panneau nominatif"],
    includesEn: ["Professional driver", "Air-conditioned vehicle", "Flight tracking", "Name sign"],
    includesAr: ["سائق محترف", "سيارة مكيفة", "تتبع الرحلة", "لافتة بالاسم"],
    includesEs: ["Conductor profesional", "Vehículo climatizado", "Seguimiento de vuelo", "Cartel con nombre"],
    gradient: "from-ochre/20 via-sand/30 to-charcoal/10",
    accentColor: "#C1652F",
  },

  // ADRENALINE
  {
    id: "agafay-pack",
    category: "adrenaline",
    slug: "pack-agafay",
    nameKey: "Pack Désert Agafay",
    price: 65,
    currency: "€",
    durationFr: "Journée complète",
    durationEn: "Full day",
    durationAr: "يوم كامل",
    durationEs: "Día completo",
    descriptionFr: "L'expérience Agafay par excellence : quad dans les collines pierreuses, balade en dromadaire au coucher du soleil, dîner show berbère sous les étoiles.",
    descriptionEn: "The quintessential Agafay experience: quad in the stony hills, camel ride at sunset, Berber dinner show under the stars.",
    descriptionAr: "تجربة أقفاي بامتياز: دراجة رباعية في التلال الحجرية، ركوب الجمال عند الغروب، عشاء شو أمازيغي تحت النجوم.",
    descriptionEs: "La experiencia Agafay por excelencia: quad por las colinas pedregosas, paseo en dromedario al atardecer, cena show bereber bajo las estrellas.",
    includesFr: ["Quad 1h", "Dromadaire 30 min", "Dîner show berbère", "Transport A/R Marrakech", "Thé à la menthe"],
    includesEn: ["Quad 1h", "Camel 30 min", "Berber dinner show", "Round-trip from Marrakech", "Mint tea"],
    includesAr: ["دراجة رباعية ساعة", "جمل 30 دقيقة", "عشاء شو أمازيغي", "نقل ذهاب وإياب من مراكش", "شاي بالنعناع"],
    includesEs: ["Quad 1h", "Dromedario 30 min", "Cena show bereber", "Transporte ida y vuelta desde Marrakech", "Té de menta"],
    gradient: "from-[#C1652F]/30 via-[#E8DCC8]/20 to-[#B8934A]/20",
    accentColor: "#C1652F",
    featured: true,
  },
  {
    id: "hot-air-balloon",
    category: "adrenaline",
    slug: "montgolfiere",
    nameKey: "Montgolfière Atlas",
    price: 180,
    currency: "€",
    durationFr: "1h de vol (départ à l'aube)",
    durationEn: "1h flight (dawn departure)",
    durationAr: "ساعة طيران (إقلاع عند الفجر)",
    durationEs: "1h de vuelo (salida al amanecer)",
    descriptionFr: "Survolez les plaines de Marrakech et les contreforts de l'Atlas dans le silence de l'aube dorée. Une heure suspendue entre ciel et terre.",
    descriptionEn: "Soar over the plains of Marrakech and the Atlas foothills in the silence of the golden dawn. One hour suspended between sky and earth.",
    descriptionAr: "حلّق فوق سهول مراكش وسفوح الأطلس في صمت الفجر الذهبي. ساعة معلقة بين السماء والأرض.",
    descriptionEs: "Sobrevuela las llanuras de Marrakech y las estribaciones del Atlas en el silencio del amanecer dorado. Una hora suspendida entre el cielo y la tierra.",
    includesFr: ["Vol en montgolfière 1h", "Certificat de vol", "Petit déjeuner marocain", "Transport A/R", "Champagne à l'atterrissage"],
    includesEn: ["1h balloon flight", "Flight certificate", "Moroccan breakfast", "Round-trip transfer", "Champagne on landing"],
    includesAr: ["رحلة منطاد ساعة", "شهادة الطيران", "إفطار مغربي", "نقل ذهاب وإياب", "شمبانيا عند الهبوط"],
    includesEs: ["Vuelo en globo 1h", "Certificado de vuelo", "Desayuno marroquí", "Transporte ida y vuelta", "Champán al aterrizar"],
    gradient: "from-[#B8934A]/25 via-[#E8DCC8]/30 to-sky-200/20",
    accentColor: "#B8934A",
    featured: true,
  },
  {
    id: "paragliding",
    category: "adrenaline",
    slug: "parapente",
    nameKey: "Parapente Atlas",
    price: 80,
    currency: "€",
    durationFr: "~30 min de vol",
    durationEn: "~30 min flight",
    durationAr: "~30 دقيقة طيران",
    durationEs: "~30 min de vuelo",
    descriptionFr: "Décollez des hauteurs de l'Atlas et planez au-dessus des vallées berbères. Moniteur diplômé, équipement certifié.",
    descriptionEn: "Take off from the heights of the Atlas and glide over Berber valleys. Certified instructor, certified equipment.",
    descriptionAr: "انطلق من ارتفاعات الأطلس وانزلق فوق الوديان الأمازيغية. مدرب معتمد، معدات معتمدة.",
    descriptionEs: "Despega desde las alturas del Atlas y planea sobre los valles bereberes. Instructor titulado, equipo certificado.",
    includesFr: ["Vol tandem avec moniteur", "Équipement complet", "Transport depuis Marrakech", "Photos/vidéos incluses"],
    includesEn: ["Tandem flight with instructor", "Full equipment", "Transfer from Marrakech", "Photos/videos included"],
    includesAr: ["طيران ثنائي مع المدرب", "معدات كاملة", "نقل من مراكش", "صور/فيديوهات مشمولة"],
    includesEs: ["Vuelo en tándem con instructor", "Equipo completo", "Traslado desde Marrakech", "Fotos/vídeos incluidos"],
    gradient: "from-[#2B2521]/15 via-[#C1652F]/15 to-[#E8DCC8]/20",
    accentColor: "#2B2521",
  },
  {
    id: "buggy",
    category: "adrenaline",
    slug: "buggy",
    nameKey: "Buggy Agafay",
    price: 80,
    currency: "€",
    durationFr: "1h ou 2h",
    durationEn: "1h or 2h",
    durationAr: "ساعة أو ساعتان",
    durationEs: "1h o 2h",
    descriptionFr: "Pilotez un buggy à travers les pistes de l'Agafay. Petit Buggy (2h) ou Grand Buggy (1h / 2h) — adrénaline garantie dans un paysage lunaire.",
    descriptionEn: "Drive a buggy through the Agafay trails. Small Buggy (2h) or Large Buggy (1h / 2h) — adrenaline guaranteed in a lunar landscape.",
    descriptionAr: "قُد سيارة باغي عبر مسالك أقفاي. باغي صغير (ساعتان) أو كبير (ساعة / ساعتان) — أدرينالين مضمون في منظر كالقمر.",
    descriptionEs: "Conduce un buggy por las pistas de Agafay. Buggy pequeño (2h) o grande (1h / 2h) — adrenalina garantizada en un paisaje lunar.",
    includesFr: ["Buggy avec casque et gants", "Briefing sécurité", "Accompagnateur guide", "Transport A/R Marrakech"],
    includesEn: ["Buggy with helmet & gloves", "Safety briefing", "Guide escort", "Round-trip from Marrakech"],
    includesAr: ["باغي مع خوذة وقفازات", "إحاطة السلامة", "مرافق مرشد", "نقل ذهاب وإياب من مراكش"],
    includesEs: ["Buggy con casco y guantes", "Briefing de seguridad", "Guía acompañante", "Transporte ida y vuelta desde Marrakech"],
    gradient: "from-[#C1652F]/20 via-[#B8934A]/15 to-[#2B2521]/10",
    accentColor: "#C1652F",
  },
  {
    id: "quad",
    category: "adrenaline",
    slug: "quad",
    nameKey: "Quad Agafay",
    price: 40,
    currency: "€",
    durationFr: "1h ou 2h",
    durationEn: "1h or 2h",
    durationAr: "ساعة أو ساعتان",
    durationEs: "1h o 2h",
    descriptionFr: "Quad biking dans le désert minéral d'Agafay. Pilotage accessible à tous niveaux, paysage spectaculaire.",
    descriptionEn: "Quad biking in the mineral desert of Agafay. Suitable for all levels, spectacular scenery.",
    descriptionAr: "دراجة رباعية في صحراء أقفاي المعدنية. مناسب لجميع المستويات، مشهد رائع.",
    descriptionEs: "Quad por el desierto mineral de Agafay. Apto para todos los niveles, paisaje espectacular.",
    includesFr: ["Quad + équipement", "Moniteur accompagnateur", "Transport A/R Marrakech"],
    includesEn: ["Quad + equipment", "Escort monitor", "Round-trip from Marrakech"],
    includesAr: ["دراجة رباعية + معدات", "مرافق", "نقل ذهاب وإياب من مراكش"],
    includesEs: ["Quad + equipo", "Monitor acompañante", "Transporte ida y vuelta desde Marrakech"],
    gradient: "from-[#E8DCC8]/30 via-[#C1652F]/15 to-[#B8934A]/20",
    accentColor: "#C1652F",
  },
  {
    id: "camel",
    category: "adrenaline",
    slug: "dromadaire",
    nameKey: "Balade à Dromadaire",
    price: 25,
    currency: "€",
    durationFr: "1h",
    durationEn: "1h",
    durationAr: "ساعة",
    durationEs: "1h",
    descriptionFr: "Une heure de balade en dromadaire dans la Palmeraie ou l'Agafay. Moment de sérénité dans un cadre authentique.",
    descriptionEn: "One hour camel ride in the Palmery or Agafay. A moment of serenity in an authentic setting.",
    descriptionAr: "ساعة من ركوب الجمال في الواحة أو أقفاي. لحظة من الهدوء في بيئة أصيلة.",
    descriptionEs: "Una hora de paseo en dromedario en la Palmeraie o Agafay. Un momento de serenidad en un entorno auténtico.",
    includesFr: ["Balade guidée 1h", "Accompagnateur chamelier", "Thé à la menthe offert"],
    includesEn: ["Guided 1h ride", "Camel handler escort", "Complimentary mint tea"],
    includesAr: ["جولة مرشدة ساعة", "مرافق راعي الجمال", "شاي بالنعناع مجاني"],
    includesEs: ["Paseo guiado 1h", "Guía camellero", "Té de menta de cortesía"],
    gradient: "from-[#B8934A]/20 via-[#E8DCC8]/25 to-[#C1652F]/15",
    accentColor: "#B8934A",
  },

  // EXCURSIONS
  {
    id: "essaouira",
    category: "excursion",
    slug: "essaouira",
    nameKey: "Essaouira",
    price: 35,
    currency: "€",
    durationFr: "Journée (départ 8h, retour 20h)",
    durationEn: "Full day (8am – 8pm)",
    durationAr: "يوم كامل (8 صباحاً - 8 مساءً)",
    durationEs: "Día completo (8h – 20h)",
    descriptionFr: "La cité des alizés, ville bleue et blanche des artistes. Médina classée UNESCO, port de pêche, plages ventées de l'Atlantique.",
    descriptionEn: "The city of trade winds, blue and white artists' city. UNESCO-listed medina, fishing port, windy Atlantic beaches.",
    descriptionAr: "مدينة الرياح التجارية، المدينة الزرقاء والبيضاء للفنانين. مدينة قديمة مدرجة في اليونسكو، ميناء صيد، شواطئ أطلسية.",
    descriptionEs: "La ciudad de los alisios, ciudad azul y blanca de los artistas. Medina declarada Patrimonio UNESCO, puerto pesquero, playas atlánticas.",
    includesFr: ["Transport A/R climatisé", "Guide francophone", "Temps libre pour déjeuner"],
    includesEn: ["A/C round-trip transport", "French-speaking guide", "Free time for lunch"],
    includesAr: ["نقل ذهاب وإياب مكيف", "مرشد يتحدث العربية", "وقت حر للغداء"],
    includesEs: ["Transporte A/R climatizado", "Guía hispanohablante", "Tiempo libre para almorzar"],
    gradient: "from-blue-100/30 via-[#E8DCC8]/20 to-[#C1652F]/10",
    accentColor: "#2B2521",
    featured: true,
  },
  {
    id: "ouzoud",
    category: "excursion",
    slug: "ouzoud",
    nameKey: "Cascades d'Ouzoud",
    price: 25,
    currency: "€",
    durationFr: "Journée (départ 8h, retour 19h)",
    durationEn: "Full day (8am – 7pm)",
    durationAr: "يوم كامل (8 صباحاً - 7 مساءً)",
    durationEs: "Día completo (8h – 19h)",
    descriptionFr: "Les plus belles chutes d'eau d'Afrique du Nord — 110 mètres de cascade dans un canyon verdoyant habité par des singes magots.",
    descriptionEn: "The most beautiful waterfalls in North Africa — 110 meters of cascade in a lush canyon inhabited by Barbary macaques.",
    descriptionAr: "أجمل شلالات شمال أفريقيا — 110 أمتار من الشلال في وادٍ أخضر يسكنه قرود المكاك.",
    descriptionEs: "Las cascadas más bellas del norte de África — 110 metros de cascada en un cañón verde habitado por macacos de Berbería.",
    includesFr: ["Transport A/R", "Guide local", "Balade en barque (optionnel)", "Temps libre"],
    includesEn: ["Round-trip transport", "Local guide", "Boat ride (optional)", "Free time"],
    includesAr: ["نقل ذهاب وإياب", "مرشد محلي", "رحلة قارب (اختياري)", "وقت حر"],
    includesEs: ["Transporte ida y vuelta", "Guía local", "Paseo en barca (opcional)", "Tiempo libre"],
    gradient: "from-green-100/20 via-[#E8DCC8]/20 to-[#B8934A]/15",
    accentColor: "#2B2521",
  },
  {
    id: "ourika",
    category: "excursion",
    slug: "vallee-ourika",
    nameKey: "Vallée de l'Ourika",
    price: 20,
    currency: "€",
    durationFr: "Demi-journée ou journée",
    durationEn: "Half-day or full day",
    durationAr: "نصف يوم أو يوم كامل",
    durationEs: "Medio día o día completo",
    descriptionFr: "À 1h de Marrakech, la vallée berbère de l'Ourika offre ses terrasses de thé, ses souks du dimanche et ses vues sur le Toubkal.",
    descriptionEn: "One hour from Marrakech, the Berber Ourika valley offers its tea terraces, Sunday souks and views of Toubkal.",
    descriptionAr: "على بعد ساعة من مراكش، تقدم وادي أوريكا الأمازيغي مقاهي الشاي وأسواق الأحد ومناظر جبل توبقال.",
    descriptionEs: "A 1h de Marrakech, el valle bereber de Ourika ofrece sus terrazas de té, sus zocos del domingo y sus vistas del Toubkal.",
    includesFr: ["Transport A/R", "Guide berbère local", "Visite de maison berbère", "Dégustation produits locaux"],
    includesEn: ["Round-trip transport", "Local Berber guide", "Berber house visit", "Local products tasting"],
    includesAr: ["نقل ذهاب وإياب", "مرشد أمازيغي محلي", "زيارة منزل أمازيغي", "تذوق المنتجات المحلية"],
    includesEs: ["Transporte ida y vuelta", "Guía bereber local", "Visita a casa bereber", "Degustación de productos locales"],
    gradient: "from-[#E8DCC8]/30 via-green-50/20 to-[#B8934A]/15",
    accentColor: "#2B2521",
  },
  {
    id: "ait-ben-haddou",
    category: "excursion",
    slug: "ait-ben-haddou",
    nameKey: "Aït Ben Haddou & Ouarzazate",
    price: 45,
    currency: "€",
    durationFr: "Journée complète (9h – 21h)",
    durationEn: "Full day (9am – 9pm)",
    durationAr: "يوم كامل (9 صباحاً - 9 مساءً)",
    durationEs: "Día completo (9h – 21h)",
    descriptionFr: "Franchissez le col du Tichka, découvrez la ksar d'Aït Ben Haddou (UNESCO) et les studios de cinéma de Ouarzazate, décor de Game of Thrones.",
    descriptionEn: "Cross the Tichka pass, discover the Aït Ben Haddou ksar (UNESCO) and Ouarzazate film studios, backdrop of Game of Thrones.",
    descriptionAr: "اعبر ممر تيشكا، اكتشف قصر آيت بن حدو (يونسكو) واستوديوهات ورزازات، خلفية مسلسل Game of Thrones.",
    descriptionEs: "Cruza el paso Tichka, descubre el ksar de Aït Ben Haddou (UNESCO) y los estudios de cine de Ouarzazate, escenario de Juego de Tronos.",
    includesFr: ["Transport A/R climatisé", "Guide diplômé", "Entrée sites", "Déjeuner restaurant local"],
    includesEn: ["A/C round-trip transport", "Licensed guide", "Site entrances", "Local restaurant lunch"],
    includesAr: ["نقل ذهاب وإياب مكيف", "مرشد مرخص", "دخول المواقع", "غداء مطعم محلي"],
    includesEs: ["Transporte A/R climatizado", "Guía titulado", "Entradas a los sitios", "Almuerzo en restaurante local"],
    gradient: "from-[#C1652F]/25 via-[#E8DCC8]/20 to-[#B8934A]/20",
    accentColor: "#C1652F",
    featured: true,
  },

  // DESERT TOURS
  {
    id: "zagora",
    category: "desert",
    slug: "zagora-2j-1n",
    nameKey: "Zagora Desert",
    price: 150,
    currency: "€",
    durationFr: "2 jours / 1 nuit",
    durationEn: "2 days / 1 night",
    durationAr: "يومان / ليلة",
    durationEs: "2 días / 1 noche",
    descriptionFr: "L'initiation idéale au Grand Sud : les dunes de Chegaga, une nuit en campement berbère sous un ciel d'étoiles, et le silence absolu du désert.",
    descriptionEn: "The ideal introduction to the Great South: Chegaga dunes, a night in a Berber camp under a sky full of stars, and the absolute silence of the desert.",
    descriptionAr: "المقدمة المثالية للجنوب الكبير: كثبان شقاقا، ليلة في مخيم أمازيغي تحت سماء مليئة بالنجوم، وصمت الصحراء المطلق.",
    descriptionEs: "La introducción ideal al Gran Sur: dunas de Chegaga, una noche en un campamento bereber bajo un cielo estrellado y el silencio absoluto del desierto.",
    includesFr: ["Transport 4x4 privé", "Hôtel ou riad 1 nuit", "Nuit en campement", "Repas inclus (dîner + petit-déj)", "Guide francophone"],
    includesEn: ["Private 4x4 transport", "Hotel or riad 1 night", "Camp night", "Meals included (dinner + breakfast)", "French-speaking guide"],
    includesAr: ["نقل خاص رباعي الدفع", "فندق أو رياض ليلة", "ليلة في المخيم", "وجبات مشمولة (عشاء + إفطار)", "مرشد يتحدث العربية"],
    includesEs: ["Transporte 4x4 privado", "Hotel o riad 1 noche", "Noche en campamento", "Comidas incluidas (cena + desayuno)", "Guía hispanohablante"],
    gradient: "from-[#C1652F]/30 via-[#B8934A]/25 to-[#2B2521]/20",
    accentColor: "#C1652F",
    featured: true,
  },
  {
    id: "merzouga",
    category: "desert",
    slug: "merzouga-3j-2n",
    nameKey: "Merzouga Erg Chebbi",
    price: 250,
    currency: "€",
    durationFr: "3 jours / 2 nuits",
    durationEn: "3 days / 2 nights",
    durationAr: "3 أيام / ليلتان",
    durationEs: "3 días / 2 noches",
    descriptionFr: "Le produit phare d'Ochre Morocco. Les légendaires dunes de l'Erg Chebbi (150m), lever de soleil sur la mer de sable, bivouac de luxe, musique gnaoua au feu de camp.",
    descriptionEn: "Ochre Morocco's flagship product. The legendary dunes of Erg Chebbi (150m), sunrise over the sea of sand, luxury bivouac, gnaoua music by the campfire.",
    descriptionAr: "المنتج الرائد لـ Ochre Morocco. الكثبان الأسطورية لعرق الشبي (150م)، شروق الشمس على بحر الرمال، بيواك فاخر، موسيقى كناوة على نار المخيم.",
    descriptionEs: "El producto estrella de Ochre Morocco. Las legendarias dunas del Erg Chebbi (150m), amanecer sobre el mar de arena, bivouac de lujo, música gnaoua junto a la hoguera.",
    includesFr: ["Transport 4x4 privé (A/R Marrakech)", "2 nuits hébergement (riad + bivouac luxe)", "Tous repas", "Dromadaire au coucher de soleil", "Guide francophone certifié", "Visites en route (Drâa, Todra)"],
    includesEn: ["Private 4x4 (round-trip Marrakech)", "2 nights accommodation (riad + luxury bivouac)", "All meals", "Camel ride at sunset", "Certified French-speaking guide", "En-route visits (Drâa, Todra)"],
    includesAr: ["سيارة خاصة رباعية الدفع (ذهاب وإياب من مراكش)", "ليلتان إقامة (رياض + بيواك فاخر)", "جميع الوجبات", "ركوب جمل عند الغروب", "مرشد معتمد يتحدث العربية", "زيارات على الطريق (درعة، تودرة)"],
    includesEs: ["4x4 privado (ida y vuelta Marrakech)", "2 noches alojamiento (riad + bivouac de lujo)", "Todas las comidas", "Paseo en dromedario al atardecer", "Guía hispanohablante certificado", "Visitas en ruta (Draa, Todra)"],
    gradient: "from-[#B8934A]/35 via-[#C1652F]/25 to-[#2B2521]/25",
    accentColor: "#B8934A",
    featured: true,
  },
];

export const getActivitiesByCategory = (category: Category) =>
  activities.filter((a) => a.category === category);

export const getFeaturedActivities = () =>
  activities.filter((a) => a.featured);

export const getActivityBySlug = (slug: string) =>
  activities.find((a) => a.slug === slug);
